$(function(){
	$("#pic1").mousedown(function(){
		$(this).css("background","#E4E4E4");
	});
	$("#pic2").mousedown(function(){
		$(this).css("background","#E4E4E4");
	});
	$("#pic3").mousedown(function(){
		$(this).css("background","#E4E4E4");
	});
	$("#pic4").mousedown(function(){
		$(this).css("background","#E4E4E4");
	});
	$("#pic1").click(function(){
		$(this).css("background","#FFFFFF");
		$(window).attr('location','index.html');
	});
	$("#pic2").click(function(){
		$(this).css("background","#FFFFFF");
		$(window).attr('location','case.php');
	});
	$("#pic3").click(function(){
		$(this).css("background","#FFFFFF");
		$(window).attr('location','jfshop.php');
	});
	$("#pic4").click(function(){
		$(this).css("background","#FFFFFF");
		$(window).attr('location','my.php');
	});
	$(".main_div").mousedown(function(){
		$(this).css("background","#E4E4E4");
	});
});

